from typing import List

from pydantic import BaseModel, Field


class MedicalQuery(BaseModel):
    """
    Medic consult model that represents the query structure made by an user
    to the medical interaction assistant.
    """
    query: str = Field(..., description="The medical query made by the user.")
    session_id: str = Field(..., description="The session ID to maintain conversation context.")

class MedicalResponse(BaseModel):
    """
    Medic response model that represents the response structure given by the
    medical interaction assistant to the user.
    """
    response: str = Field(..., description="The response generated by the medical interaction assistant.")

class SessionInfo(BaseModel):
    """
    Model representing the information of a chat session, including the session ID.
    """
    session_id: str = Field(..., description="The unique identifier for the chat session.")