name: Tests Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Ejecutar pruebas unitarias
      run: |
        pipenv run pytest tests/unit/

    - name: Ejecutar pruebas de integración
      run: |
        pipenv run pytest tests/integration/