import logging
from pathlib import Path

from app.rag.cleaners.prospecto_cleaner import ProspectoCleaner
from app.rag.embedding.document_embedder import DocumentEmbedder
from app.rag.embedding.embedding_strategy.sentence_transformer_strategy import SentenceTransformerStrategy
from app.rag.loaders.prospecto_loader import ProspectoLoader
from app.rag.readers.pdf_reader import PDFReader
from app.service.assistance.groq_rag_assistance import GroqRAGAssistance
from app.service.vector_store.vectore_store_manager import VectorStoreManager


class RAGManager:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(RAGManager, cls).__new__(cls)
            cls._instance.assistance = None
            cls._instance._initialized = False

        return cls._instance
    
    def __init__(self):
        pass
    
    def initialize(self):
        """
        Initialize the RAGManager with necessary components.
        This method should be called once during application startup.
        """

        if self._initialized:
            logging.warning("RAGManager is already initialized.")
            return
        
        logging.info("Initializing RAGManager with vector store and embedding strategy.")
        
        # 1. Prepare vector database with prospecto documets
        strategy = SentenceTransformerStrategy(model_name="all-MiniLM-L6-v2")
        vector_store_manager = VectorStoreManager()

        if vector_store_manager.is_empty():
            logging.info("Vector store is empty. Starting to load documents" \
                         " and generate embeddings before initializing RAGManager.")
            
            prospectos_pdf_path = Path("data/prospectos_pdfs")

            if any(prospectos_pdf_path.glob("*.pdf")):
                logging.info(f"Found PDF documents in {prospectos_pdf_path}." \
                             " Proceeding with loading and embedding.")
                
                prospecto_cleaner = ProspectoCleaner()
                pdf_reader = PDFReader()
                document_embedder = DocumentEmbedder(strategy=strategy)

                for pdf_file in prospectos_pdf_path.glob("*.pdf"):
                    logging.info(f"Processing document: {pdf_file}")
                    loader = ProspectoLoader(reader=pdf_reader,
                                            cleaner=prospecto_cleaner,
                                            source=str(pdf_file),
                                            cima_id=pdf_file.stem)
                    documents = loader.create_document()
                    final_documents = document_embedder.generate_embeddings(documents)
                    vector_store_manager.save_documents(final_documents)

        else:
            logging.debug("Vector store already has documents. Skipping loading"\
                         " and embedding generation.")
            
        # 2. Prepare history store
        """
        logging.info("Setting up history store with MongoDB.")

        db_instance = MongoDBClient().medical_db
        history_repository = MongoHistoryRepo(db_client=db_instance)
        history_service = HistoryService(history_repository=history_repository)
        """

        # 3. Initialize RAG assistance
        logging.info("Initializing GroqRAGAssistance.")
        self.assistance = GroqRAGAssistance(
                            vector_store=vector_store_manager,
                            embedding_strategy=strategy,
                            db_connection=None#history_service
                        )

        self._initialized = True

    async def get_response(self, query: str, session_id: str) -> str:
        """
        Get a response from the RAG assistance based on the query and session ID.

        Arguments:
            query (str): The user's query.
            session_id (str): The unique identifier for the chat session.

        Returns:
            str: The response generated by the RAG assistance.
        """
        if not self._initialized:
            raise Exception("RAGManager is not initialized. "\
                            "Call initialize() before using this method.")
        
        logging.info(f"Getting response for query: '{query}' in session: '{session_id}'")        
        return await self.assistance.ask(query=query, session_id=session_id)
        